name: Python with Flask

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clone:

    runs-on: self-hosted

    steps:
      - name: Clone project
        run: /home/ubuntu/deploy-actions/python/clone.sh ${GITHUB_REF##*/}
      - name: Build with Node
        run: /home/ubuntu/deploy-actions/python/build.sh ${GITHUB_REF##*/}
      - name: Deploy
        run: /home/ubuntu/deploy-actions/python/deploy.sh ${GITHUB_REF##*/}
